baseURL: https://galt.me
languageCode: en-us
title: "Adam Galt"
theme: "toha"

enableEmoji: true

params: 
  background: "images/site/background.jpg"
  logo:
    main: /images/site/favicon.png
    inverted: /images/site/favicon.png
    favicon: /images/site/favicon.png

  customMenus:
  - name: Send me files
    url: https://share.galt.me/app/share/CTLDMbr6YDH-cxMBMTixrgm-25ouRVr3ARb-2d3Wu5kBU4a

  - name: "Blog"
    url: https://blog.galt.me
    